name: make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Set up Go 1.14.x
        uses: actions/setup-go@v1
        env:
          GOPATH: ${{ github.workspace }}
          GO111MODULE: off
        with:
          go-version: 1.14
      - name: dependencies
        run: make go-dependencies   
        
      - name: verify
        run: make verify  

      - name: make all
        run: make all    
