
name: make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: dependencies
        run: |
          GOBIN=$PWD/bin 
          make go-dependencies   
          GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.26.0
          make all
  
