
name: make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - name: Set up Go 1.14.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        run: |
          wget https://github.com/operator-framework/operator-sdk/releases/download/v0.15.2/operator-sdk-v0.15.2-x86_64-linux-gnu
          sudo mv operator-sdk-v0.15.2-x86_64-linux-gnu /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          make build 
      - uses: actions/checkout@master         
      - name: bump version and push tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GH_TOKEN }}
      - name: helm 
        run: |
          wget https://github.com/operator-framework/operator-sdk/releases/download/v0.15.2/operator-sdk-v0.15.2-x86_64-linux-gnu
          sudo mv operator-sdk-v0.15.2-x86_64-linux-gnu /usr/local/bin/operator-sdk
          sudo chmod +x /usr/local/bin/operator-sdk
          curl -Lo helm.tar.gz https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz && tar xzfv helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin/
          make verify install container-runtime-build container-runtime-images helm-package helm-deploy        
