name: make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14.x
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Make 
      - uses: actions/checkout@v1.2.0
      - run: make all         
